version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=localhost

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - BE_SERVER_PORT=4000
    depends_on:
      - db
